.PHONY: clean All

All:
	@echo "----------Building project:[ CentsChallenge - Debug ]----------"
	@cd "CentsChallenge" && "$(MAKE)" -f  "CentsChallenge.mk"
clean:
	@echo "----------Cleaning project:[ CentsChallenge - Debug ]----------"
	@cd "CentsChallenge" && "$(MAKE)" -f  "CentsChallenge.mk" clean
