.PHONY: clean All

All:
	@echo "----------Building project:[ TemplateMacOSProject - Debug ]----------"
	@cd "TemplateMacOSProject" && "$(MAKE)" -f  "TemplateMacOSProject.mk"
clean:
	@echo "----------Cleaning project:[ TemplateMacOSProject - Debug ]----------"
	@cd "TemplateMacOSProject" && "$(MAKE)" -f  "TemplateMacOSProject.mk" clean
